In [71]:
import pandas as pd
import numpy as np
from pythainlp import word_tokenize
import warnings
import re
import string
warnings.filterwarnings('ignore')

In [72]:
df_crime = pd.read_csv('../Data/THR_DLR_CLA_V2_Primary_Full_EA.csv')
df_crime

News Title  \
0     ตร.นนท์จับหนุ่มแท็กซี่ขโมยเนื้อหมูของร้านตามสั...   
1     ครอบครัว "ฮ้อแสงชัย" เชื่อคดี "เบนซ์ชนฟอร์ด" จ...   
2     ตร.แจง ดารากุเรื่องเป็นเซียนหวย อาจเข้าข่ายผิด...   
3     หนุ่มชาวบ้านที่ถูกยิงดับใต้สะพานที่บาเจาะ ตร.ค...   
4     ผกก.สายไหม มอบสิ่งของผู้สูงอายุ เนื่องในวันเฉล...   
...                                                 ...   
8562  ตร.แจง ดารากุเรื่องเป็นเซียนหวย อาจเข้าข่ายผิด...   
8563  หนุ่มชาวบ้านที่ถูกยิงดับใต้สะพานที่บาเจาะ ตร.ค...   
8564  ผกก.สายไหม มอบสิ่งของผู้สูงอายุ เนื่องในวันเฉล...   
8565  ในหลวงพระราชทานตราสัญลักษณ์ประจำหน่วยปฏิบัติกา...   
8566  จี๊ปเหินข้ามเกาะกลางถนน ชนรถพ่วง 22 ล้อ บรรทุก...   

                                             News_Intro  \
0     ตำรวจ สภ.รัตนาธิเบศร์ จับกุมโชเฟอร์แท็กซี่ตามห...   
1     น้องสาวและครอบครัวฮ้อแสงชัย ขอบคุณกระบวนการยุต...   
2     รองโฆษก ตร.แจงกรณีสื่อแฉดาราสร้างเรื่องหลอกลวง...   
3     พบศพหนุ่มวัย 22 ปี ถูกยิงด้วยปืน 9 มม. ตาย 1 ศ...   
4     ผกก.สน.สายไหม นำทีมข้าราชการตำรวจในสังกัด และเ...   
...                                                 ...   
8562  รองโฆษก ตร.แจงกรณีสื่อแฉดาราสร้างเรื่องหลอกลวง...   
8563  พบศพหนุ่มวัย 22 ปี ถูกยิงด้วยปืน 9 มม. ตาย 1 ศ...   
8564  ผกก.สน.สายไหม นำทีมข้าราชการตำรวจในสังกัด และเ...   
8565  พล.ต.ต.จิรภพ ภูริเดช ผบก.ป. พร้อมข้าราชการตำรว...   
8566  อุบัติเหตุบนถนนสาย 304 กบินทร์บุรี-ฉะเชิงเทรา ...   

                                              News_Desc  \
0     ตำรวจ สภ.รัตนาธิเบศร์ จับกุมโชเฟอร์แท็กซี่ตามห...   
1     น้องสาวและครอบครัวฮ้อแสงชัย ขอบคุณกระบวนการยุต...   
2     รองโฆษก ตร.แจงกรณีสื่อแฉดาราสร้างเรื่องหลอกลวง...   
3     พบศพหนุ่มวัย 22 ปี ถูกยิงด้วยปืน 9 มม. ตาย 1 ศ...   
4     ผกก.สน.สายไหม นำทีมข้าราชการตำรวจในสังกัด และเ...   
...                                                 ...   
8562  รองโฆษก ตร.แจงกรณีสื่อแฉดาราสร้างเรื่องหลอกลวง...   
8563  พบศพหนุ่มวัย 22 ปี ถูกยิงด้วยปืน 9 มม. ตาย 1 ศ...   
8564  ผกก.สน.สายไหม นำทีมข้าราชการตำรวจในสังกัด และเ...   
8565  พล.ต.ต.จิรภพ ภูริเดช ผบก.ป. พร้อมข้าราชการตำรว...   
8566  อุบัติเหตุบนถนนสาย 304 กบินทร์บุรี-ฉะเชิงเทรา ...   

                                               News_All  Gambling  Murder  \
0     ตร.นนท์จับหนุ่มแท็กซี่ขโมยเนื้อหมูของร้านตามสั...         0       0   
1     ครอบครัว "ฮ้อแสงชัย" เชื่อคดี "เบนซ์ชนฟอร์ด" จ...         0       0   
2     ตร.แจง ดารากุเรื่องเป็นเซียนหวย อาจเข้าข่ายผิด...         0       0   
3     หนุ่มชาวบ้านที่ถูกยิงดับใต้สะพานที่บาเจาะ ตร.ค...         0       1   
4     ผกก.สายไหม มอบสิ่งของผู้สูงอายุ เนื่องในวันเฉล...         0       0   
...                                                 ...       ...     ...   
8562  ตร.แจง ดารากุเรื่องเป็นเซียนหวย อาจเข้าข่ายผิด...         0       0   
8563  หนุ่มชาวบ้านที่ถูกยิงดับใต้สะพานที่บาเจาะ ตร.ค...         0       1   
8564  ผกก.สายไหม มอบสิ่งของผู้สูงอายุ เนื่องในวันเฉล...         0       0   
8565  ในหลวงพระราชทานตราสัญลักษณ์ประจำหน่วยปฏิบัติกา...         0       0   
8566  จี๊ปเหินข้ามเกาะกลางถนน ชนรถพ่วง 22 ล้อ บรรทุก...         0       0   

      Sexual Abuse  Theft/Burglary  Drug  Battery/Assault  Accident  Non-Crime  
0                0               1     0                0         0          0  
1                0               0     0                0         1          0  
2                0               0     0                0         0          1  
3                0               0     1                0         0          0  
4                0               0     0                0         0          1  
...            ...             ...   ...              ...       ...        ...  
8562             0               0     0                0         0          1  
8563             0               0     1                1         0          0  
8564             0               0     0                0         0          1  
8565             0               0     0                0         0          1  
8566             0               0     0                0         1          0  

[8567 rows x 12 colu

In [73]:
# 0:1 = title, 1:2 = ../Data/THR_DLR_CLA_V2_Primary.csvIntro, 2:3 = Desc, 3:4 = All, 4: Labels <Target>
X = df_crime.iloc[:,3:4].values
Y = df_crime.iloc[:, 4:].values

In [74]:
len(Y[334])
Y[334]

array([0, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [75]:
def clean_msg(msg):
    # ลบ text ที่อยู่ในวงเล็บ <> ทั้งหมด
    msg = re.sub(r'<.*?>','', msg)
    # ลบ hashtag
    msg = re.sub(r'#','',msg)
    # ลบ เครื่องหมายคำพูด (punctuation)
    for c in string.punctuation:
        msg = re.sub(r'\{}'.format(c),'',msg)
    # ลบ separator เช่น \n \t
    msg = ' '.join(msg.split())
    return msg

In [76]:
clean_text_arr = []
for i in range(len(X)):
    clean_text = clean_msg(X[i][0])
    clean_text_arr.append(clean_text)

In [77]:
arr = []
for i in range(len(X)):
    token = word_tokenize(clean_text_arr[i], keep_whitespace=False)
    arr.append(token)

In [78]:
from sklearn.feature_extraction.text import CountVectorizer
tokens_list_j = [','.join(tkn) for tkn in arr]
cvec = CountVectorizer(analyzer=lambda x:x.split(','))
c_feat = cvec.fit_transform(tokens_list_j)

In [79]:
from sklearn.feature_extraction.text import TfidfVectorizer
tvec = TfidfVectorizer(analyzer=lambda x:x.split(','))
t_feat = tvec.fit_transform(tokens_list_j)

In [80]:
TFIDF_Data = t_feat.toarray()

In [81]:
len(TFIDF_Data[100])

40276

In [82]:
X[334]

array(['ภูธรภาค 1 จับหนุ่มขับฟอร์จูนเนอร์ ลอบขนยาบ้ายึดได้ 4.5 ล้านเม็ดจากชายแดน ตำรวจภูธรภาค 1 จับกุมหนุ่มเมืองชลขับฟอร์จูนเนอร์ลอบขนยาบ้า 4.5 ล้านเม็ด รวม 11 กระสอบพร้อมคุมไปค้นบ้านย่านบางบ่อเจอยาอีก 1 พันเม็ด รับสารภาพขนยามาจากชายแดนภาคเหนือ เข้าอีสาน ก่อนรอส่งลงใต้เมื่อเวลา 10.00 น. วันที่ 6 ต.ค.63 ที่ลานอเนกประสงค์ บชภ.1 พล.ต.อ.มนู เมฆหมอก รอง ผบ.ตร. พล.ต.ท.อำพล บัวรับพร ผบช.ภ.1 พล.ต.ต.สุภธีร์ บุญครอง รอง ผบช.ภ.1 ร่วมกันแถลงข่าวผลการจับกุมตัวนายสาธิต ดือขุนทด หรือติ๋ว อายุ 31 ปี ชาว จ.ชลบุรี พร้อมของกลางยาบ้า 4,500,000 เ... ตำรวจภูธรภาค 1 จับกุมหนุ่มเมืองชลขับฟอร์จูนเนอร์ลอบขนยาบ้า 4.5 ล้านเม็ด รวม 11 กระสอบพร้อมคุมไปค้นบ้านย่านบางบ่อเจอยาอีก 1 พันเม็ด รับสารภาพขนยามาจากชายแดนภาคเหนือ เข้าอีสาน ก่อนรอส่งลงใต้เมื่อเวลา 10.00 น. วันที่ 6 ต.ค.63 ที่ลานอเนกประสงค์ บชภ.1 พล.ต.อ.มนู เมฆหมอก รอง ผบ.ตร. พล.ต.ท.อำพล บัวรับพร ผบช.ภ.1 พล.ต.ต.สุภธีร์ บุญครอง รอง ผบช.ภ.1 ร่วมกันแถลงข่าวผลการจับกุมตัวนายสาธิต ดือขุนทด หรือติ๋ว อายุ 31 ปี ชาว จ.ชลบุรี พร้อมของกลางยาบ้า 4,500,000 เม็ด ยาอี 1,000 

In [83]:
Y[334]

array([0, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [84]:
Y_label_data = np.array(Y)

In [85]:
from sklearn.model_selection import KFold
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn import svm
from sklearn.multioutput import ClassifierChain, MultiOutputClassifier
import xgboost as xgb
Labellist = ['Gambling','Murder','Sexual Abuse','Theft/Burglary','Drug','Battery/Assault','Accident','Non-Crime']
Kfold_classification_report_data = []
Y_Ground_Truth_data = []
Y_Predicted_data = []
kf = KFold(n_splits=5, random_state=42, shuffle=True)
kf.get_n_splits(X)
for train_index, test_index in kf.split(TFIDF_Data):
    X_train, X_test, y_train, y_test = TFIDF_Data[train_index], TFIDF_Data[test_index], Y_label_data[train_index], Y_label_data[test_index]
    clf_Kfold = xgb.XGBClassifier(objective='binary:logistic',random_state=42,tree_method='gpu_hist')
    clf_Kfold = MultiOutputClassifier(clf_Kfold)
    clf_Kfold.fit(X_train,y_train)
    result = clf_Kfold.predict(X_test)
    Y_Ground_Truth_data.append(y_test)
    Y_Predicted_data.append(result)
    Kfold_classification_report_data.append(classification_report(y_test, result,output_dict = True,target_names=Labellist))

In [86]:
Y_Ground_Truth_data[2]

array([[0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 1, 0, ..., 1, 0, 0]], dtype=int64)

In [87]:
Y_Predicted_data[2]

array([[0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 1, 0, ..., 0, 0, 0]], dtype=int64)

In [88]:
import seaborn as sns

All_KFold = True
Index = 2 # range: 0-9
if All_KFold is True:
    count = 1
    for i in range(5):
        print('=-=-=-=-=-==-=-=-=-=-=-=-=-= ' + str(count) + ' =-=-=-=-=-==-=-=-=-=-=-=-=-=')
        print(classification_report(Y_Ground_Truth_data[i], Y_Predicted_data[i],target_names=Labellist))
        print(confusion_matrix(Y_Ground_Truth_data[i].argmax(axis=1), Y_Predicted_data[i].argmax(axis=1)))
        count += 1
else:
    print(('=-=-=-=-=-==-=-=-=-=-=-=-=-= ' + str(Index) + ' =-=-=-=-=-==-=-=-=-=-=-=-=-='))
    print(classification_report(Y_Ground_Truth_data[Index], Y_Predicted_data[Index],target_names=Labellist))
    cm = confusion_matrix(Y_Ground_Truth_data[Index].argmax(axis=1), Y_Predicted_data[Index].argmax(axis=1))
    sns.heatmap(cm, annot=True, xticklabels = Labellist, yticklabels = Labellist)

=-=-=-=-=-==-=-=-=-=-=-=-=-= 1 =-=-=-=-=-==-=-=-=-=-=-=-=-=
                 precision    recall  f1-score   support

       Gambling       0.93      0.83      0.88        52
         Murder       0.88      0.87      0.87       473
   Sexual Abuse       0.91      0.84      0.87       140
 Theft/Burglary       0.92      0.63      0.75       165
           Drug       0.95      0.81      0.87       221
Battery/Assault       0.78      0.64      0.70       372
       Accident       0.94      0.74      0.83       153
      Non-Crime       0.90      0.76      0.82       290

      micro avg       0.88      0.76      0.82      1866
      macro avg       0.90      0.76      0.83      1866
   weighted avg       0.88      0.76      0.82      1866
    samples avg       0.72      0.69      0.69      1866

[[219  17   4   6   2  12   1  16]
 [ 30 403   2   0   3  20   7   1]
 [ 12   3 107   0   1   0   0   0]
 [ 34   0   0  94   0   6   0   3]
 [  8   2   2   0 155   7   1   2]
 [ 21  14   0   3   2

Convert Dict Data into List Data

In [89]:
# ! accuracy at the last for easier to code
Main_Class_Data = [[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[]]
Class_list = ['Gambling','Murder','Sexual Abuse','Theft/Burglary','Drug','Battery/Assault','Accident','Non-Crime','micro avg','macro avg','weighted avg','samples avg']
Sub_Class_list = ['precision','recall','f1-score','support']
for i in range(5):
    for j in range(12):
        for k in range(4):
            Main_Class_Data[j][k].append(Kfold_classification_report_data[i][Class_list[j]][Sub_Class_list[k]])

Calculate the Avg of all classification_report

In [90]:
from statistics import mean
Result_Class_Data = [[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[]]
for i in range(12):
    for j in range(4):
        Result_Class_Data[i][j].append(round(mean(Main_Class_Data[i][j]),2))

Print the Avg of all classification report

In [92]:
Class_list = ['Gambling','Murder','Sexual Abuse','Theft/Burglary','Drug','Battery/Assault','Accident','Non-Crime']
Avg_list = ['micro avg','macro avg','weighted avg','samples avg']
# print(' '*20 + 'precision' + ' '*5 + 'recall' + ' '*5 + 'f1-score' + ' '*5 + 'support')
print(f'=-=-=-=-= Avg Classification Report of 5 KFold =-=-=-=-=')
for i in range(8):
    print(Class_list[i] + ':' + ' '*5 + str(Result_Class_Data[i][0][0]) + ' '*5 + str(Result_Class_Data[i][1][0]) + ' '*5 + str(Result_Class_Data[i][2][0]) + ' '*5 + str(Result_Class_Data[i][3][0]))
for i in range(8,12):
    print(Avg_list[i-8] + ':' + ' '*5 + str(Result_Class_Data[i][0][0]) + ' '*5 + str(Result_Class_Data[i][1][0]) + ' '*5 + str(Result_Class_Data[i][2][0]) + ' '*5 + str(Result_Class_Data[i][3][0]))

=-=-=-=-= Avg Classification Report of 5 KFold =-=-=-=-=
Gambling:     0.97     0.78     0.86     49.8
Murder:     0.89     0.87     0.88     511.4
Sexual Abuse:     0.93     0.82     0.87     134.6
Theft/Burglary:     0.91     0.66     0.76     154.8
Drug:     0.94     0.8     0.87     207.8
Battery/Assault:     0.79     0.66     0.72     377.8
Accident:     0.91     0.73     0.81     144.2
Non-Crime:     0.89     0.75     0.82     281.2
micro avg:     0.89     0.77     0.82     1861.6
macro avg:     0.91     0.76     0.82     1861.6
weighted avg:     0.89     0.77     0.82     1861.6
samples avg:     0.71     0.69     0.69     1861.6
