In [376]:
import pickle
import numpy as np
import pandas as pd

In [377]:
id_list = ['018_087_123','022_094','041_050_095','042_072_169','058_093_144']
filename = id_list[0]
df_base = pd.read_csv('../Data/Junior_Data/' + filename + '.csv')
df_base

News_Title  \
0     งามไส้! บุกค้นสำนักงานหมู่บ้านต้นแบบ เจอโพยหวย...   
1     ตำรวจ PCT บุกบ้านย่านลำลูกกา เปิดเว็บพนันหวยออ...   
2     หนุ่มขับเก๋งชนหลักกิโลยับแต่รอดตาย แต่ถูกจับ เ...   
3     ผบช.น. ปลื้ม 191 โชว์รวบแก๊งค้ายา ยึดของกลางอื...   
4     สืบภ.8รวบแอดมินเว็บพนันufa666.win คาห้องเช่าพบ...   
...                                                 ...   
1545  คุมลูกทรพียิงเจ้าโลกพ่อดับทำแผน ญาติไทยมุงแช่ง...   
1546  ประสิทธิ์ เจียวก๊ก มอบตัวฉ้อโกงประชาชน มั่นใจถ...   
1547  ประสิทธิ์ เจียวก๊ก เตรียมมอบตัว ส่วน 4 ผู้ต้อง...   
1548  กองปราบจับแก๊งตุ๋นขายทองผ่านเฟซบุ๊ก เหยื่อกว่า...   
1549  ตร.จับมิจฉาชีพสาวหลอกขายของออนไลน์ เชิดเงินเหย...   

                                             News_Intro  \
0     ตำรวจบุกค้นสำนักงานคณะกรรมการหมู่บ้านต้นแบบ เจ...   
1     ตำรวจ PCT ชุด 4 ได้เข้าจับกุมเว็บพนันออนไลน์ H...   
2     หนุ่มดวงซวยขับเก๋งชนหลักกิโล จนรถกระเด็นหงายท้...   
3     "บิ๊กราญ" นำทัพตำรวจนครบาลโชว์ผลงาน รวบแก๊งค้า...   
4     พล.ต.ท.อำพล บัวรับพร ผบช.ภ.8 สั่งฝ่ายสืบสวนบุก...   
...                                                 ...   
1545  ตร.ทุ่งสง คุมตัวลูกทรพียิงเจ้าโลกพ่อดับทำแผน โ...   
1546  ประสิทธิ์ เจียวก๊ก มอบตัวแล้วที่กองปราบฯ มาพร้...   
1547  ประสิทธิ์ เจียวก๊ก ประธานโครงการคืนคุณแผ่นดิน ...   
1548  ตำรวจกองปราบปราม ตามรวบหนึ่งในผู้ร่วมขบวนการหล...   
1549  กองปราบตามรวบ "สาวมิจฉาชีพ" หลอกขายสินค้าออนไล...   

                                              News_Desc  \
0     เมื่อวันที่ 17 พ.ย. พ.ต.อ.บัญชา คล้ายน้อย ผกก....   
1     ตำรวจ PCT ชุด 4 ได้เข้าจับกุมเว็บพนันออนไลน์ H...   
2     หนุ่มดวงซวยขับเก๋งชนหลักกิโล จนรถกระเด็นหงายท้...   
3     "บิ๊กราญ" นำทัพตำรวจนครบาลโชว์ผลงาน รวบแก๊งค้า...   
4     เมื่อวันที่ 16 พ.ย. พล.ต.ท.อำพล บัวรับพร ผบช.ภ...   
...                                                 ...   
1545  ตร.ทุ่งสง คุมตัวลูกทรพียิงเจ้าโลกพ่อดับทำแผน โ...   
1546  ประสิทธิ์ เจียวก๊ก มอบตัวแล้วที่กองปราบฯ ยันโด...   
1547  ประสิทธิ์ เจียวก๊ก ประธานโครงการคืนคุณแผ่นดิน ...   
1548  ตำรวจกองปราบปราม ตามรวบหนึ่งในผู้ร่วมขบวนการหล...   
1549  กองปราบตามรวบ "สาวมิจฉาชีพ" หลอกขายสินค้าออนไล...   

                                               News_All  Gambling  Murder  \
0     งามไส้! บุกค้นสำนักงานหมู่บ้านต้นแบบ เจอโพยหวย...         1       0   
1     ตำรวจ PCT บุกบ้านย่านลำลูกกา เปิดเว็บพนันหวยออ...         1       0   
2     หนุ่มขับเก๋งชนหลักกิโลยับแต่รอดตาย แต่ถูกจับ เ...         0       0   
3     ผบช.น. ปลื้ม 191 โชว์รวบแก๊งค้ายา ยึดของกลางอื...         0       0   
4     สืบภ.8รวบแอดมินเว็บพนันufa666.win คาห้องเช่าพบ...         1       0   
...                                                 ...       ...     ...   
1545  คุมลูกทรพียิงเจ้าโลกพ่อดับทำแผน ญาติไทยมุงแช่ง...         0       1   
1546  ประสิทธิ์ เจียวก๊ก มอบตัวฉ้อโกงประชาชน มั่นใจถ...         0       0   
1547  ประสิทธิ์ เจียวก๊ก เตรียมมอบตัว ส่วน 4 ผู้ต้อง...         0       0   
1548  กองปราบจับแก๊งตุ๋นขายทองผ่านเฟซบุ๊ก เหยื่อกว่า...         0       0   
1549  ตร.จับมิจฉาชีพสาวหลอกขายของออนไลน์ เชิดเงินเหย...         0       0   

      Sexual Abuse  Theft / Burglary  Drug  Battery / Assault  Accident  \
0                0                 0     0                  0         0   
1                0                 0     0                  0         0   
2                0                 0     1                  0         1   
3                0                 0     1                  0         0   
4                0                 0     0                  0         0   
...            ...               ...   ...                ...       ...   
1545             0                 0     0                  0         0   
1546             0                 0     0                  0         0   
1547             0                 0     0                  0         0   
1548             0                 0     0                  0         0   
1549             0                 0     0                  0         0   

      Non-crime  
0             0  
1             0  
2             0  
3             0  
4 

In [378]:
ground_truth = df_base.iloc[:,4:].values
df_base.drop(df_base.columns[[4,5,6,7,8,9,10,11]],axis = 1, inplace= True)
print(ground_truth)

[[1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [379]:
df_base

News_Title  \
0     งามไส้! บุกค้นสำนักงานหมู่บ้านต้นแบบ เจอโพยหวย...   
1     ตำรวจ PCT บุกบ้านย่านลำลูกกา เปิดเว็บพนันหวยออ...   
2     หนุ่มขับเก๋งชนหลักกิโลยับแต่รอดตาย แต่ถูกจับ เ...   
3     ผบช.น. ปลื้ม 191 โชว์รวบแก๊งค้ายา ยึดของกลางอื...   
4     สืบภ.8รวบแอดมินเว็บพนันufa666.win คาห้องเช่าพบ...   
...                                                 ...   
1545  คุมลูกทรพียิงเจ้าโลกพ่อดับทำแผน ญาติไทยมุงแช่ง...   
1546  ประสิทธิ์ เจียวก๊ก มอบตัวฉ้อโกงประชาชน มั่นใจถ...   
1547  ประสิทธิ์ เจียวก๊ก เตรียมมอบตัว ส่วน 4 ผู้ต้อง...   
1548  กองปราบจับแก๊งตุ๋นขายทองผ่านเฟซบุ๊ก เหยื่อกว่า...   
1549  ตร.จับมิจฉาชีพสาวหลอกขายของออนไลน์ เชิดเงินเหย...   

                                             News_Intro  \
0     ตำรวจบุกค้นสำนักงานคณะกรรมการหมู่บ้านต้นแบบ เจ...   
1     ตำรวจ PCT ชุด 4 ได้เข้าจับกุมเว็บพนันออนไลน์ H...   
2     หนุ่มดวงซวยขับเก๋งชนหลักกิโล จนรถกระเด็นหงายท้...   
3     "บิ๊กราญ" นำทัพตำรวจนครบาลโชว์ผลงาน รวบแก๊งค้า...   
4     พล.ต.ท.อำพล บัวรับพร ผบช.ภ.8 สั่งฝ่ายสืบสวนบุก...   
...                                                 ...   
1545  ตร.ทุ่งสง คุมตัวลูกทรพียิงเจ้าโลกพ่อดับทำแผน โ...   
1546  ประสิทธิ์ เจียวก๊ก มอบตัวแล้วที่กองปราบฯ มาพร้...   
1547  ประสิทธิ์ เจียวก๊ก ประธานโครงการคืนคุณแผ่นดิน ...   
1548  ตำรวจกองปราบปราม ตามรวบหนึ่งในผู้ร่วมขบวนการหล...   
1549  กองปราบตามรวบ "สาวมิจฉาชีพ" หลอกขายสินค้าออนไล...   

                                              News_Desc  \
0     เมื่อวันที่ 17 พ.ย. พ.ต.อ.บัญชา คล้ายน้อย ผกก....   
1     ตำรวจ PCT ชุด 4 ได้เข้าจับกุมเว็บพนันออนไลน์ H...   
2     หนุ่มดวงซวยขับเก๋งชนหลักกิโล จนรถกระเด็นหงายท้...   
3     "บิ๊กราญ" นำทัพตำรวจนครบาลโชว์ผลงาน รวบแก๊งค้า...   
4     เมื่อวันที่ 16 พ.ย. พล.ต.ท.อำพล บัวรับพร ผบช.ภ...   
...                                                 ...   
1545  ตร.ทุ่งสง คุมตัวลูกทรพียิงเจ้าโลกพ่อดับทำแผน โ...   
1546  ประสิทธิ์ เจียวก๊ก มอบตัวแล้วที่กองปราบฯ ยันโด...   
1547  ประสิทธิ์ เจียวก๊ก ประธานโครงการคืนคุณแผ่นดิน ...   
1548  ตำรวจกองปราบปราม ตามรวบหนึ่งในผู้ร่วมขบวนการหล...   
1549  กองปราบตามรวบ "สาวมิจฉาชีพ" หลอกขายสินค้าออนไล...   

                                               News_All  
0     งามไส้! บุกค้นสำนักงานหมู่บ้านต้นแบบ เจอโพยหวย...  
1     ตำรวจ PCT บุกบ้านย่านลำลูกกา เปิดเว็บพนันหวยออ...  
2     หนุ่มขับเก๋งชนหลักกิโลยับแต่รอดตาย แต่ถูกจับ เ...  
3     ผบช.น. ปลื้ม 191 โชว์รวบแก๊งค้ายา ยึดของกลางอื...  
4     สืบภ.8รวบแอดมินเว็บพนันufa666.win คาห้องเช่าพบ...  
...                                                 ...  
1545  คุมลูกทรพียิงเจ้าโลกพ่อดับทำแผน ญาติไทยมุงแช่ง...  
1546  ประสิทธิ์ เจียวก๊ก มอบตัวฉ้อโกงประชาชน มั่นใจถ...  
1547  ประสิทธิ์ เจียวก๊ก เตรียมมอบตัว ส่วน 4 ผู้ต้อง...  
1548  กองปราบจับแก๊งตุ๋นขายทองผ่านเฟซบุ๊ก เหยื่อกว่า...  
1549  ตร.จับมิจฉาชีพสาวหลอกขายของออนไลน์ เชิดเงินเหย...  

[1550 rows x 4 columns]

In [380]:
pickle_prediction = np.load('../WangChanBERT/pickle_files/Prob_Predict_' + filename + '.pickle', allow_pickle=True)
pickle_prediction = np.round(pickle_prediction)
pickle_prediction = pickle_prediction.astype(int)

In [381]:
print(pickle_prediction)

[[1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 ...
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]]


In [382]:
resulttype = []
for i in range(len(pickle_prediction)):
    counter = 0
    for j in range(8):
        if (pickle_prediction[i][j] != ground_truth[i][j]):
            counter = counter + 1
    if (counter == 0):
        resulttype.append('Correct')
    else:
        if (ground_truth[i].tolist().count(1) == 0):
            resulttype.append('GT_AllZeroes')
        elif (ground_truth[i].tolist().count(1) < pickle_prediction[i].tolist().count(1)):
            resulttype.append('MisType1')
        elif (ground_truth[i].tolist().count(1) > pickle_prediction[i].tolist().count(1)):
            resulttype.append('MisType2')
        else:
            resulttype.append('MisType3')
        


In [383]:
ground_truth_str_arr = []
for i in range(len(ground_truth)):
    ground_truth_str  = ' '.join([str(x) for x in ground_truth[i]])
    ground_truth_str_arr.append(ground_truth_str)

In [384]:
prediction_str_arr = []
for i in range(len(pickle_prediction)):
    prediction_str  = ' '.join([str(x) for x in pickle_prediction[i]])
    prediction_str_arr.append(prediction_str)

In [385]:
b = pd.DataFrame(ground_truth_str_arr,columns= ['Ground Truth'])
c = pd.DataFrame(prediction_str_arr,columns= ['Prediction'])
d = pd.DataFrame(resulttype,columns= ['ResultType'])

In [386]:
df_result = pd.concat([df_base,b,c,d],axis=1)

In [387]:
df_result

News_Title  \
0     งามไส้! บุกค้นสำนักงานหมู่บ้านต้นแบบ เจอโพยหวย...   
1     ตำรวจ PCT บุกบ้านย่านลำลูกกา เปิดเว็บพนันหวยออ...   
2     หนุ่มขับเก๋งชนหลักกิโลยับแต่รอดตาย แต่ถูกจับ เ...   
3     ผบช.น. ปลื้ม 191 โชว์รวบแก๊งค้ายา ยึดของกลางอื...   
4     สืบภ.8รวบแอดมินเว็บพนันufa666.win คาห้องเช่าพบ...   
...                                                 ...   
1545  คุมลูกทรพียิงเจ้าโลกพ่อดับทำแผน ญาติไทยมุงแช่ง...   
1546  ประสิทธิ์ เจียวก๊ก มอบตัวฉ้อโกงประชาชน มั่นใจถ...   
1547  ประสิทธิ์ เจียวก๊ก เตรียมมอบตัว ส่วน 4 ผู้ต้อง...   
1548  กองปราบจับแก๊งตุ๋นขายทองผ่านเฟซบุ๊ก เหยื่อกว่า...   
1549  ตร.จับมิจฉาชีพสาวหลอกขายของออนไลน์ เชิดเงินเหย...   

                                             News_Intro  \
0     ตำรวจบุกค้นสำนักงานคณะกรรมการหมู่บ้านต้นแบบ เจ...   
1     ตำรวจ PCT ชุด 4 ได้เข้าจับกุมเว็บพนันออนไลน์ H...   
2     หนุ่มดวงซวยขับเก๋งชนหลักกิโล จนรถกระเด็นหงายท้...   
3     "บิ๊กราญ" นำทัพตำรวจนครบาลโชว์ผลงาน รวบแก๊งค้า...   
4     พล.ต.ท.อำพล บัวรับพร ผบช.ภ.8 สั่งฝ่ายสืบสวนบุก...   
...                                                 ...   
1545  ตร.ทุ่งสง คุมตัวลูกทรพียิงเจ้าโลกพ่อดับทำแผน โ...   
1546  ประสิทธิ์ เจียวก๊ก มอบตัวแล้วที่กองปราบฯ มาพร้...   
1547  ประสิทธิ์ เจียวก๊ก ประธานโครงการคืนคุณแผ่นดิน ...   
1548  ตำรวจกองปราบปราม ตามรวบหนึ่งในผู้ร่วมขบวนการหล...   
1549  กองปราบตามรวบ "สาวมิจฉาชีพ" หลอกขายสินค้าออนไล...   

                                              News_Desc  \
0     เมื่อวันที่ 17 พ.ย. พ.ต.อ.บัญชา คล้ายน้อย ผกก....   
1     ตำรวจ PCT ชุด 4 ได้เข้าจับกุมเว็บพนันออนไลน์ H...   
2     หนุ่มดวงซวยขับเก๋งชนหลักกิโล จนรถกระเด็นหงายท้...   
3     "บิ๊กราญ" นำทัพตำรวจนครบาลโชว์ผลงาน รวบแก๊งค้า...   
4     เมื่อวันที่ 16 พ.ย. พล.ต.ท.อำพล บัวรับพร ผบช.ภ...   
...                                                 ...   
1545  ตร.ทุ่งสง คุมตัวลูกทรพียิงเจ้าโลกพ่อดับทำแผน โ...   
1546  ประสิทธิ์ เจียวก๊ก มอบตัวแล้วที่กองปราบฯ ยันโด...   
1547  ประสิทธิ์ เจียวก๊ก ประธานโครงการคืนคุณแผ่นดิน ...   
1548  ตำรวจกองปราบปราม ตามรวบหนึ่งในผู้ร่วมขบวนการหล...   
1549  กองปราบตามรวบ "สาวมิจฉาชีพ" หลอกขายสินค้าออนไล...   

                                               News_All     Ground Truth  \
0     งามไส้! บุกค้นสำนักงานหมู่บ้านต้นแบบ เจอโพยหวย...  1 0 0 0 0 0 0 0   
1     ตำรวจ PCT บุกบ้านย่านลำลูกกา เปิดเว็บพนันหวยออ...  1 0 0 0 0 0 0 0   
2     หนุ่มขับเก๋งชนหลักกิโลยับแต่รอดตาย แต่ถูกจับ เ...  0 0 0 0 1 0 1 0   
3     ผบช.น. ปลื้ม 191 โชว์รวบแก๊งค้ายา ยึดของกลางอื...  0 0 0 0 1 0 0 0   
4     สืบภ.8รวบแอดมินเว็บพนันufa666.win คาห้องเช่าพบ...  1 0 0 0 0 0 0 0   
...                                                 ...              ...   
1545  คุมลูกทรพียิงเจ้าโลกพ่อดับทำแผน ญาติไทยมุงแช่ง...  0 1 0 0 0 0 0 0   
1546  ประสิทธิ์ เจียวก๊ก มอบตัวฉ้อโกงประชาชน มั่นใจถ...  0 0 0 0 0 0 0 0   
1547  ประสิทธิ์ เจียวก๊ก เตรียมมอบตัว ส่วน 4 ผู้ต้อง...  0 0 0 0 0 0 0 0   
1548  กองปราบจับแก๊งตุ๋นขายทองผ่านเฟซบุ๊ก เหยื่อกว่า...  0 0 0 0 0 0 0 0   
1549  ตร.จับมิจฉาชีพสาวหลอกขายของออนไลน์ เชิดเงินเหย...  0 0 0 0 0 0 0 0   

           Prediction    ResultType  
0     1 0 0 0 0 0 0 0       Correct  
1     1 0 0 0 0 0 0 0       Correct  
2     0 0 0 0 1 0 1 0       Correct  
3     0 0 0 0 1 0 0 0       Correct  
4     1 0 0 0 0 0 0 0       Correct  
...               ...           ...  
1545  0 1 0 0 0 0 0 0       Correct  
1546  0 0 0 1 0 0 0 0  GT_AllZeroes  
1547  1 0 0 1 0 0 0 0  GT_AllZeroes  
1548  1 0 0 1 0 0 0 0  GT_AllZeroes  
1549  1 0 0 1 0 0 0 0  GT_AllZeroes  

[1550 rows x 7 columns]

In [388]:
df_result = df_result[df_result.ResultType != 'Correct']

In [389]:
df_result

News_Title  \
13    Truck Power! บช.น.แนะเส้นทางเลี่ยง ‘ม็อบรถบรรท...   
14    เตือนภัยแก๊งคอลเซ็นเตอร์ ตัดต่อคลิปเสียงรองโฆษ...   
16    แม่เลี้ยงแสบ! บังคับลูกสาววัย14ค้าประเวณี พาส่...   
18    รวบอดีตแก๊งยากูซ่าตัวท็อป ตั้งบริษัทผลิตถุงมือ...   
21    จับโดยละม่อม ผู้ต้องหาฉ้อโกง ตร.ตามเจอเบาะแส โ...   
...                                                 ...   
1544  ทภ.2 ตั้งกรรมการสอบ พ.ต.หญิง เอี่ยวแก๊ง "ประสิ...   
1546  ประสิทธิ์ เจียวก๊ก มอบตัวฉ้อโกงประชาชน มั่นใจถ...   
1547  ประสิทธิ์ เจียวก๊ก เตรียมมอบตัว ส่วน 4 ผู้ต้อง...   
1548  กองปราบจับแก๊งตุ๋นขายทองผ่านเฟซบุ๊ก เหยื่อกว่า...   
1549  ตร.จับมิจฉาชีพสาวหลอกขายของออนไลน์ เชิดเงินเหย...   

                                             News_Intro  \
13    กองบัญชาการตำรวจนครบาล แจงเส้นทาง กิจกรรมคาร์ม...   
14    รองโฆษก ตร.เตือนภัยประชาชนอย่าหลงเชื่อแก๊งคอลเ...   
16    กองปราบฯ รวบแม่เลี้ยงแสบ บังคับลูกเลี้ยงวัย 14...   
18    ตำรวจ ปคบ.-ปอศ. จับอดีตแก๊งยากูซ่า ตั้งบริษัทข...   
21    หนุ่มท่าศาลา นครศรีธรรมราช ตกเป็นผู้ต้องหาฉ้อโ...   
...                                                 ...   
1544  กองทัพภาคที่ 2 ตั้งกรรมการสอบ "พันตรีหญิง" เอี...   
1546  ประสิทธิ์ เจียวก๊ก มอบตัวแล้วที่กองปราบฯ มาพร้...   
1547  ประสิทธิ์ เจียวก๊ก ประธานโครงการคืนคุณแผ่นดิน ...   
1548  ตำรวจกองปราบปราม ตามรวบหนึ่งในผู้ร่วมขบวนการหล...   
1549  กองปราบตามรวบ "สาวมิจฉาชีพ" หลอกขายสินค้าออนไล...   

                                              News_Desc  \
13    เมื่อวันที่ 15 พ.ย. ผู้สื่อข่าวรายงานว่า กองบั...   
14    เมื่อวันที่ 15 พ.ย. ที่สำนักงานตำรวจแห่งชาติ (...   
16    เมื่อวันที่ 15 พ.ย. ที่กองบังคับการปราบปราม พล...   
18    เมื่อวันที่ 15 พ.ย. ที่กองบังคับการปราบปราม (บ...   
21    หนุ่มท่าศาลา นครศรีธรรมราช ตกเป็นผู้ต้องหาฉ้อโ...   
...                                                 ...   
1544  กองทัพภาคที่ 2 ตั้งกรรมการสอบ "พันตรีหญิง" เอี...   
1546  ประสิทธิ์ เจียวก๊ก มอบตัวแล้วที่กองปราบฯ ยันโด...   
1547  ประสิทธิ์ เจียวก๊ก ประธานโครงการคืนคุณแผ่นดิน ...   
1548  ตำรวจกองปราบปราม ตามรวบหนึ่งในผู้ร่วมขบวนการหล...   
1549  กองปราบตามรวบ "สาวมิจฉาชีพ" หลอกขายสินค้าออนไล...   

                                               News_All     Ground Truth  \
13    Truck Power! บช.น.แนะเส้นทางเลี่ยง ‘ม็อบรถบรรท...  0 0 0 0 0 0 0 0   
14    เตือนภัยแก๊งคอลเซ็นเตอร์ ตัดต่อคลิปเสียงรองโฆษ...  0 0 0 0 0 0 0 0   
16    แม่เลี้ยงแสบ! บังคับลูกสาววัย14ค้าประเวณี พาส่...  0 0 0 0 0 0 0 0   
18    รวบอดีตแก๊งยากูซ่าตัวท็อป ตั้งบริษัทผลิตถุงมือ...  0 0 0 0 0 0 0 0   
21    จับโดยละม่อม ผู้ต้องหาฉ้อโกง ตร.ตามเจอเบาะแส โ...  0 0 0 0 0 0 0 0   
...                                                 ...              ...   
1544  ทภ.2 ตั้งกรรมการสอบ พ.ต.หญิง เอี่ยวแก๊ง "ประสิ...  0 0 0 0 0 0 0 0   
1546  ประสิทธิ์ เจียวก๊ก มอบตัวฉ้อโกงประชาชน มั่นใจถ...  0 0 0 0 0 0 0 0   
1547  ประสิทธิ์ เจียวก๊ก เตรียมมอบตัว ส่วน 4 ผู้ต้อง...  0 0 0 0 0 0 0 0   
1548  กองปราบจับแก๊งตุ๋นขายทองผ่านเฟซบุ๊ก เหยื่อกว่า...  0 0 0 0 0 0 0 0   
1549  ตร.จับมิจฉาชีพสาวหลอกขายของออนไลน์ เชิดเงินเหย...  0 0 0 0 0 0 0 0   

           Prediction    ResultType  
13    0 0 0 0 0 0 0 1  GT_AllZeroes  
14    0 0 0 1 0 0 0 0  GT_AllZeroes  
16    0 0 1 0 0 0 0 0  GT_AllZeroes  
18    0 0 0 0 1 0 0 0  GT_AllZeroes  
21    0 0 0 1 0 0 0 0  GT_AllZeroes  
...               ...           ...  
1544  1 0 0 1 0 0 0 0  GT_AllZeroes  
1546  0 0 0 1 0 0 0 0  GT_AllZeroes  
1547  1 0 0 1 0 0 0 0  GT_AllZeroes  
1548  1 0 0 1 0 0 0 0  GT_AllZeroes  
1549  1 0 0 1 0 0 0 0  GT_AllZeroes  

[846 rows x 7 columns]

In [390]:
df_result.to_csv('./WangChanBERT/Error_Analysis_'+filename+'.csv',encoding = 'utf-8')